In [24]:
import numpy as np
import pandas as pd
from tqdm import tqdm

In [15]:
!ls /data2/yt8m/code/yt8m

data_converter.py  models.py  probs_100.npy  __pycache__  train.py  work_dirs
loader.py	   notebooks  probs.npy      settings.py  utils.py


In [55]:
p1 = np.load('/data2/yt8m/code/yt8m/probs.npy', allow_pickle=True)
p1[:2]

array([[6.9659978e-01, 1.3740591e-04, 1.1694086e-06, ..., 8.6689353e-05,
        6.0337617e-05, 2.5136296e-07],
       [8.1797791e-01, 4.7672194e-07, 1.8004628e-05, ..., 1.0984526e-08,
        5.2207708e-04, 1.4610782e-07]], dtype=float32)

In [53]:
p2 = np.load('/data2/yt8m/code/yt8m/rnn3_0918.npy', allow_pickle=True)
p2[:2]

array([[8.8766348e-01, 7.4459531e-05, 1.4046773e-07, ..., 1.0157839e-05,
        3.3870427e-04, 8.4951431e-08],
       [9.9903846e-01, 4.3215941e-11, 9.2645269e-09, ..., 5.1636928e-12,
        5.8856360e-05, 4.3446281e-11]], dtype=float32)

In [56]:
p = np.average([p1, p2], 0)

In [57]:
type(p)

numpy.ndarray

In [58]:
p.shape

(2038114, 1001)

In [59]:
p[:2]

array([[7.9213166e-01, 1.0593272e-04, 6.5493816e-07, ..., 4.8423597e-05,
        1.9952095e-04, 1.6815720e-07],
       [9.0850818e-01, 2.3838258e-07, 9.0069461e-06, ..., 5.4948450e-09,
        2.9046673e-04, 7.3075633e-08]], dtype=float32)

In [4]:
df_test = pd.read_csv('/data2/yt8m/3/frame/test_ids.csv')
df_test.head()

vid  start_time
0  MeVj           0
1  MeVj           5
2  MeVj          10
3  MeVj          15
4  MeVj          20

In [5]:
df_test.values[:2]

array([['MeVj', 0],
       ['MeVj', 5]], dtype=object)

In [6]:
def get_seg_id(row):
    return '{}:{}'.format(row.vid, row.start_time)

In [8]:
df_test['seg_id'] = df_test.apply(lambda x: get_seg_id(x), axis=1)
df_test.head()

vid  start_time   seg_id
0  MeVj           0   MeVj:0
1  MeVj           5   MeVj:5
2  MeVj          10  MeVj:10
3  MeVj          15  MeVj:15
4  MeVj          20  MeVj:20

In [20]:
df_test.head()

vid  start_time   seg_id
0  MeVj           0   MeVj:0
1  MeVj           5   MeVj:5
2  MeVj          10  MeVj:10
3  MeVj          15  MeVj:15
4  MeVj          20  MeVj:20

In [13]:
idx = np.argsort(p[:,1])[::-1]
idx

array([93, 92, 94, 90, 81, 91, 69, 79, 60, 95, 83, 82, 70, 96, 19, 62, 84,
       63, 78, 25, 85, 64, 37, 30, 38, 65, 61, 71, 76, 77, 49, 68, 72, 50,
       14, 98, 88, 80, 52,  0, 87, 66, 73, 89, 75, 33, 51, 44, 99,  5, 41,
       29, 31, 24, 67, 45,  6, 23, 97, 86, 48, 43, 20, 42,  3, 26,  8, 16,
       39, 74, 46, 15, 54,  7, 57, 21, 36,  2, 18, 27, 17, 47, 12, 58, 22,
       59, 11, 13, 34,  4, 53, 55, 35,  1, 40, 28, 32, 56, 10,  9])

In [12]:
p[:,1][93]

0.023245452

In [14]:
df_test.seg_id.values[idx]

array(['nBeX:165', 'nBeX:160', 'nBeX:170', 'nBeX:150', 'nBeX:105',
       'nBeX:155', 'nBeX:45', 'nBeX:95', 'nBeX:0', 'nBeX:175', 'nBeX:115',
       'nBeX:110', 'nBeX:50', 'nBeX:180', 'MeVj:95', 'nBeX:10',
       'nBeX:120', 'nBeX:15', 'nBeX:90', 'MeVj:125', 'nBeX:125',
       'nBeX:20', 'MeVj:185', 'MeVj:150', 'MeVj:190', 'nBeX:25', 'nBeX:5',
       'nBeX:55', 'nBeX:80', 'nBeX:85', 'MeVj:245', 'nBeX:40', 'nBeX:60',
       'MeVj:250', 'MeVj:70', 'nBeX:190', 'nBeX:140', 'nBeX:100',
       'MeVj:260', 'MeVj:0', 'nBeX:135', 'nBeX:30', 'nBeX:65', 'nBeX:145',
       'nBeX:75', 'MeVj:165', 'MeVj:255', 'MeVj:220', 'nBeX:195',
       'MeVj:25', 'MeVj:205', 'MeVj:145', 'MeVj:155', 'MeVj:120',
       'nBeX:35', 'MeVj:225', 'MeVj:30', 'MeVj:115', 'nBeX:185',
       'nBeX:130', 'MeVj:240', 'MeVj:215', 'MeVj:100', 'MeVj:210',
       'MeVj:15', 'MeVj:130', 'MeVj:40', 'MeVj:80', 'MeVj:195', 'nBeX:70',
       'MeVj:230', 'MeVj:75', 'MeVj:270', 'MeVj:35', 'MeVj:285',
       'MeVj:105', 'MeVj:180', 'MeV

In [21]:
def get_classes():
    df = pd.read_csv('/data2/yt8m/3/frame/classes.csv')
    c = df['class'].values.tolist()
    stoi = { c[i]: i for i in range(len(c)) }
    return c, stoi

classes, _ = get_classes()

In [22]:
classes[:2]

['none', '3']

In [23]:
print(df_test.shape, p.shape)

(2038114, 3) (2038114, 1001)


In [60]:
res = []
for i in tqdm(range(1, 1001)):
    idx = np.argsort(p[:,i])[::-1][:100000]
    best_segs = df_test.seg_id.values[idx]
    pred_str = ' '.join(best_segs)
    res.append({
        'Class': classes[i],
        'Segments': pred_str
    })


100%|██████████| 1000/1000 [05:07<00:00,  3.28it/s]


In [61]:
df_sub = pd.DataFrame(res)
df_sub.head()

Class                                           Segments
0     3  Rbop:90 1shy:15 Rbop:40 Rbop:95 Rbop:120 Rbop:...
1     7  WEoW:85 WEoW:105 WEoW:115 1yAi:15 nDT4:70 HmvV...
2     8  sYqm:60 sYqm:70 sYqm:125 sYqm:130 AoRH:185 KG7...
3    11  7Cuq:255 zdov:105 oVyD:200 CwkZ:175 zdov:40 2J...
4    12  xupR:100 FXxf:80 FXxf:135 o1QP:120 FXxf:70 odz...

In [62]:
df_sub.to_csv('sub_ens1.csv', index=False)

In [63]:
!kaggle competitions submit -c youtube8m-2019 -f sub_ens1.csv -m 'submit'

100%|████████████████████████████████████████| 810M/810M [00:37<00:00, 22.8MB/s]
Successfully submitted to The 3rd YouTube-8M Video Understanding Challenge

In [36]:
!ls -lh

total 25M
-rw-r--r-- 1 FAREAST.chec FAREAST.domain users 444K Sep 16 13:33 create_meta.ipynb
-rw-r--r-- 1 FAREAST.chec FAREAST.domain users  40K Sep 14 09:35 eda.ipynb
-rw-r--r-- 1 FAREAST.chec FAREAST.domain users  17M Sep 17 19:06 sub1_rnn3_local057_2000.csv
-rw-r--r-- 1 FAREAST.chec FAREAST.domain users 8.2M Sep 17 03:34 sub1_rnn3_local0.57.csv
-rw-r--r-- 1 FAREAST.chec FAREAST.domain users  17K Sep 17 19:06 submit.ipynb
